### ISSUE TITLE
canMoveToNextStep set to false by `next` after selecting the mission in quickstart wizard

### ISSUE THREAD

**Issue by corinnekrych** [fabric8io/fabric8-generator#51]
The wizard API for quickstart (fabric8-new-project) after selecting a quickstart mission on the next command to go to Fabric8ProjectInfoStep, returns a `valid: false` and `canMoveToNextStep: false`

See https://gist.github.com/corinnekrych/abfab9f9a8f7a7a587bca25385b57551#file-gistfile1-txt-L61-L64

This is wrong, we do not want a validation to occurs on the next.

**Comment by corinnekrych** [comment]
@jstrachan After discussing with @gastaldi it seems you can remove validation in next command like [here](https://github.com/openshiftio/launchpad-addon/blob/a9850d19836e963ae8df08da2ed49743e41e523a/src/main/java/io/openshift/launchpad/ui/booster/ProjectInfoStep.java#L171). But you need the latest version of the launchpad backend (this piece of [code](https://github.com/openshiftio/launchpad-backend/blob/master/src/main/java/io/openshift/launchpad/backend/rest/LaunchResource.java#L232)).
Let me create a separate epic to track the remove fork and mark it as dependency.

**Comment by jstrachan** [comment]
We'll also need to do a diff of the ObsidianResource to the launchpad one to see what other differences there are - we made a bunch of changes over the last 6 months to work around forge issues - particularly around adding our own commands, removing launchpad commands, removing the zips & json reporting of results & errors

**Comment by jstrachan** [comment]
Btw why do we need to disable validation on Next - how else is validate going to be called? 

Either the form should validate if we pass a 'named' value into Next - or if the validation fails (the defaulted name already exists as a git repo) then we want the invalid result & message?

**Comment by corinnekrych** [comment]
@jstrachan in the ui we chain 2 promises which end end with 2 http calls (validate and next) are done one for validate and then next see: https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/wizard/services/fabric8-app-generator.client.ts#L259
But on the addon even when we call next, validate is done (this is what i observe)

**Comment by jstrachan** [comment]
Isn't it quicker & faster just to do 1 http call to 'next & validate'?

**Comment by jstrachan** [comment]
@corinnekrych is this fixed now?

**Comment by corinnekrych** [comment]
@jstrachan not fixed. forge addon api returns false.but the ui worked around it in this PR:https://github.com/fabric8-ui/fabric8-ui/pull/1914
